#framework:
#    default_locale: en
#    translator:
#        default_path: '%kernel.project_dir%/translations'
#        fallbacks:
#            - en
#        providers:

framework:
    default_locale: fr
    translator: { paths: ['%kernel.project_dir%/translations'] }