<?php

namespace Container0WwmuQl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RQY3Y3gService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RQY3Y3g' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RQY3Y3g'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'livrerProduitRepository' => ['privates', 'App\\Repository\\LivrerProduitRepository', 'getLivrerProduitRepositoryService', true],
            'repository' => ['privates', 'App\\Repository\\ProduitRepository', 'getProduitRepositoryService', true],
            'retour' => ['privates', '.errored..service_locator.RQY3Y3g.App\\Entity\\Retour', NULL, 'Cannot autowire service ".service_locator.RQY3Y3g": it needs an instance of "App\\Entity\\Retour" but this type has been excluded in "config/services.yaml".'],
        ], [
            'livrerProduitRepository' => 'App\\Repository\\LivrerProduitRepository',
            'repository' => 'App\\Repository\\ProduitRepository',
            'retour' => 'App\\Entity\\Retour',
        ]);
    }
}
