<?php

namespace Container0WwmuQl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BpW2PiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bpW2Pi_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bpW2Pi_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'facture' => ['privates', '.errored..service_locator.bpW2Pi_.App\\Entity\\Facture', NULL, 'Cannot autowire service ".service_locator.bpW2Pi_": it needs an instance of "App\\Entity\\Facture" but this type has been excluded in "config/services.yaml".'],
            'solde' => ['privates', 'App\\Complement\\Solde', 'getSoldeService', true],
        ], [
            'facture' => 'App\\Entity\\Facture',
            'solde' => 'App\\Complement\\Solde',
        ]);
    }
}
