<?php

namespace Container0WwmuQl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AYYV_AmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.AYYV.am' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.AYYV.am'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'commande' => ['privates', '.errored..service_locator.AYYV.am.App\\Entity\\Commande', NULL, 'Cannot autowire service ".service_locator.AYYV.am": it needs an instance of "App\\Entity\\Commande" but this type has been excluded in "config/services.yaml".'],
            'repository' => ['privates', 'App\\Repository\\CommandeProduitRepository', 'getCommandeProduitRepositoryService', true],
        ], [
            'commande' => 'App\\Entity\\Commande',
            'repository' => 'App\\Repository\\CommandeProduitRepository',
        ]);
    }
}
