<?php

namespace Container0WwmuQl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0FQRyqGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0FQRyqG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0FQRyqG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repository' => ['privates', 'App\\Repository\\RetourProduitRepository', 'getRetourProduitRepositoryService', true],
            'retour' => ['privates', '.errored..service_locator.0FQRyqG.App\\Entity\\Retour', NULL, 'Cannot autowire service ".service_locator.0FQRyqG": it needs an instance of "App\\Entity\\Retour" but this type has been excluded in "config/services.yaml".'],
        ], [
            'repository' => 'App\\Repository\\RetourProduitRepository',
            'retour' => 'App\\Entity\\Retour',
        ]);
    }
}
