<?php

namespace Container0WwmuQl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_F5JWNKPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.f5JWNKP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.f5JWNKP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'critereEvaluation' => ['privates', '.errored..service_locator.f5JWNKP.App\\Entity\\CritereEvaluation', NULL, 'Cannot autowire service ".service_locator.f5JWNKP": it needs an instance of "App\\Entity\\CritereEvaluation" but this type has been excluded in "config/services.yaml".'],
        ], [
            'critereEvaluation' => 'App\\Entity\\CritereEvaluation',
        ]);
    }
}
