<?php

namespace Container0WwmuQl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_L9F73kIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.L9F73kI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.L9F73kI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'conges' => ['privates', '.errored..service_locator.L9F73kI.App\\Entity\\Conges', NULL, 'Cannot autowire service ".service_locator.L9F73kI": it needs an instance of "App\\Entity\\Conges" but this type has been excluded in "config/services.yaml".'],
        ], [
            'conges' => 'App\\Entity\\Conges',
        ]);
    }
}
