<?php

namespace Container0WwmuQl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FYOg1aHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fYOg1aH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fYOg1aH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'paie' => ['privates', '.errored..service_locator.fYOg1aH.App\\Entity\\Paie', NULL, 'Cannot autowire service ".service_locator.fYOg1aH": it needs an instance of "App\\Entity\\Paie" but this type has been excluded in "config/services.yaml".'],
        ], [
            'paie' => 'App\\Entity\\Paie',
        ]);
    }
}
