<?php

namespace Container0WwmuQl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TrbLHtService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TrbL_Ht' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TrbL_Ht'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'commande' => ['privates', '.errored..service_locator.TrbL_Ht.App\\Entity\\Commande', NULL, 'Cannot autowire service ".service_locator.TrbL_Ht": it needs an instance of "App\\Entity\\Commande" but this type has been excluded in "config/services.yaml".'],
            'comprodrepository' => ['privates', 'App\\Repository\\CommandeProduitRepository', 'getCommandeProduitRepositoryService', true],
            'livrerResteRepository' => ['privates', 'App\\Repository\\LivrerResteRepository', 'getLivrerResteRepositoryService', true],
            'repository' => ['privates', 'App\\Repository\\ProduitRepository', 'getProduitRepositoryService', true],
        ], [
            'commande' => 'App\\Entity\\Commande',
            'comprodrepository' => 'App\\Repository\\CommandeProduitRepository',
            'livrerResteRepository' => 'App\\Repository\\LivrerResteRepository',
            'repository' => 'App\\Repository\\ProduitRepository',
        ]);
    }
}
