<?php

namespace Container0WwmuQl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EZHsKb7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.EZHsKb7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.EZHsKb7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'produit' => ['privates', '.errored..service_locator.EZHsKb7.App\\Entity\\Produit', NULL, 'Cannot autowire service ".service_locator.EZHsKb7": it needs an instance of "App\\Entity\\Produit" but this type has been excluded in "config/services.yaml".'],
            'repository' => ['privates', 'App\\Repository\\StockRepository', 'getStockRepositoryService', true],
        ], [
            'produit' => 'App\\Entity\\Produit',
            'repository' => 'App\\Repository\\StockRepository',
        ]);
    }
}
