<?php

namespace Container0WwmuQl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_QbcOcOyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.QbcOcOy' shared service.
     *
     * @return \App\Controller\Security\UserPasswordEncoderInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\Security\\securityController::reset()": the $encoder argument is type-hinted with the non-existent class or interface: "App\\Controller\\Security\\UserPasswordEncoderInterface". Did you forget to add a use statement?');
    }
}
