<?php

namespace Container0WwmuQl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SKXD69hService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sKXD69h' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sKXD69h'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'reclamationRepository' => ['privates', 'App\\Repository\\ReclamationRepository', 'getReclamationRepositoryService', true],
            'user' => ['privates', '.errored..service_locator.sKXD69h.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.sKXD69h": it needs an instance of "App\\Entity\\User" but this type has been excluded in "config/services.yaml".'],
        ], [
            'reclamationRepository' => 'App\\Repository\\ReclamationRepository',
            'user' => 'App\\Entity\\User',
        ]);
    }
}
