<?php

namespace Container0WwmuQl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NttXpgMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NttXpgM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NttXpgM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'message' => ['privates', '.errored..service_locator.NttXpgM.App\\Entity\\MessageRecipient', NULL, 'Cannot autowire service ".service_locator.NttXpgM": it needs an instance of "App\\Entity\\MessageRecipient" but this type has been excluded in "config/services.yaml".'],
        ], [
            'em' => '?',
            'message' => 'App\\Entity\\MessageRecipient',
        ]);
    }
}
