<?php

namespace Container0WwmuQl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Xc_M5MvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Xc.m5Mv' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Xc.m5Mv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'livrerrepository' => ['privates', 'App\\Repository\\LivrerRepository', 'getLivrerRepositoryService', true],
            'repository' => ['privates', 'App\\Repository\\ProduitRepository', 'getProduitRepositoryService', true],
            'retour' => ['privates', '.errored..service_locator.Xc.m5Mv.App\\Entity\\Retour', NULL, 'Cannot autowire service ".service_locator.Xc.m5Mv": it needs an instance of "App\\Entity\\Retour" but this type has been excluded in "config/services.yaml".'],
            'retourProduitRepository' => ['privates', 'App\\Repository\\RetourProduitRepository', 'getRetourProduitRepositoryService', true],
        ], [
            'livrerrepository' => 'App\\Repository\\LivrerRepository',
            'repository' => 'App\\Repository\\ProduitRepository',
            'retour' => 'App\\Entity\\Retour',
            'retourProduitRepository' => 'App\\Repository\\RetourProduitRepository',
        ]);
    }
}
