<?php

namespace Container0WwmuQl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5DVS3roService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5DVS3ro' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5DVS3ro'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'produitRepository' => ['privates', 'App\\Repository\\ProduitRepository', 'getProduitRepositoryService', true],
            'repository' => ['privates', 'App\\Repository\\CommandeProduitRepository', 'getCommandeProduitRepositoryService', true],
        ], [
            'produitRepository' => 'App\\Repository\\ProduitRepository',
            'repository' => 'App\\Repository\\CommandeProduitRepository',
        ]);
    }
}
