<?php

namespace Container0WwmuQl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0BS18HQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0BS18HQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0BS18HQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'commande' => ['privates', '.errored..service_locator.0BS18HQ.App\\Entity\\Commande', NULL, 'Cannot autowire service ".service_locator.0BS18HQ": it needs an instance of "App\\Entity\\Commande" but this type has been excluded in "config/services.yaml".'],
            'comprodrepository' => ['privates', 'App\\Repository\\CommandeProduitRepository', 'getCommandeProduitRepositoryService', true],
            'livrer' => ['privates', '.errored..service_locator.0BS18HQ.App\\Entity\\Livrer', NULL, 'Cannot autowire service ".service_locator.0BS18HQ": it needs an instance of "App\\Entity\\Livrer" but this type has been excluded in "config/services.yaml".'],
            'livrerProduitRepository' => ['privates', 'App\\Repository\\LivrerProduitRepository', 'getLivrerProduitRepositoryService', true],
            'repository' => ['privates', 'App\\Repository\\ProduitRepository', 'getProduitRepositoryService', true],
        ], [
            'commande' => 'App\\Entity\\Commande',
            'comprodrepository' => 'App\\Repository\\CommandeProduitRepository',
            'livrer' => 'App\\Entity\\Livrer',
            'livrerProduitRepository' => 'App\\Repository\\LivrerProduitRepository',
            'repository' => 'App\\Repository\\ProduitRepository',
        ]);
    }
}
