<?php

namespace Container0WwmuQl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Wz47QTFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Wz47QTF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Wz47QTF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'transfertRepository' => ['privates', 'App\\Repository\\TransfertRepository', 'getTransfertRepositoryService', true],
        ], [
            'transfertRepository' => 'App\\Repository\\TransfertRepository',
        ]);
    }
}
