<?php

namespace Container0WwmuQl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_A2hTFDLService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.A2hTFDL' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.A2hTFDL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'produitrepo' => ['privates', 'App\\Repository\\PromotionProduitRepository', 'getPromotionProduitRepositoryService', true],
            'promotion' => ['privates', '.errored..service_locator.A2hTFDL.App\\Entity\\Promotion', NULL, 'Cannot autowire service ".service_locator.A2hTFDL": it needs an instance of "App\\Entity\\Promotion" but this type has been excluded in "config/services.yaml".'],
        ], [
            'produitrepo' => 'App\\Repository\\PromotionProduitRepository',
            'promotion' => 'App\\Entity\\Promotion',
        ]);
    }
}
