<?php

namespace Container0WwmuQl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_P6oBFqBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.p6oBFqB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.p6oBFqB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'remboursement' => ['privates', '.errored..service_locator.p6oBFqB.App\\Entity\\Remboursement', NULL, 'Cannot autowire service ".service_locator.p6oBFqB": it needs an instance of "App\\Entity\\Remboursement" but this type has been excluded in "config/services.yaml".'],
        ], [
            'remboursement' => 'App\\Entity\\Remboursement',
        ]);
    }
}
