<?php

namespace Container0WwmuQl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_36EpRsAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.36EpRsA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.36EpRsA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'achatRepository' => ['privates', 'App\\Repository\\AchatRepository', 'getAchatRepositoryService', true],
        ], [
            'achatRepository' => 'App\\Repository\\AchatRepository',
        ]);
    }
}
