<?php

namespace Container0WwmuQl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BpNOuybService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BpNOuyb' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BpNOuyb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'typeConge' => ['privates', '.errored..service_locator.BpNOuyb.App\\Entity\\TypeConge', NULL, 'Cannot autowire service ".service_locator.BpNOuyb": it needs an instance of "App\\Entity\\TypeConge" but this type has been excluded in "config/services.yaml".'],
        ], [
            'typeConge' => 'App\\Entity\\TypeConge',
        ]);
    }
}
