<?php

namespace Container0WwmuQl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CxwWrHGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CxwWrHG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CxwWrHG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'achat' => ['privates', '.errored..service_locator.CxwWrHG.App\\Entity\\Achat', NULL, 'Cannot autowire service ".service_locator.CxwWrHG": it needs an instance of "App\\Entity\\Achat" but this type has been excluded in "config/services.yaml".'],
        ], [
            'achat' => 'App\\Entity\\Achat',
        ]);
    }
}
