<?php

namespace Container0WwmuQl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GP7DK30Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GP7DK30' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.GP7DK30'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'banqueRepository' => ['privates', 'App\\Repository\\BanqueRepository', 'getBanqueRepositoryService', true],
        ], [
            'banqueRepository' => 'App\\Repository\\BanqueRepository',
        ]);
    }
}
