<?php

namespace Container0WwmuQl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAvoir2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.hxmsnV3.App\Entity\Avoir' shared service.
     *
     * @return \App\Entity\Avoir
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.hxmsnV3": it needs an instance of "App\\Entity\\Avoir" but this type has been excluded in "config/services.yaml".');
    }
}
