<?php

namespace Container0WwmuQl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaieControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\PaieController' shared autowired service.
     *
     * @return \App\Controller\PaieController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'PaieController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'PaieService.php';

        $container->services['App\\Controller\\PaieController'] = $instance = new \App\Controller\PaieController(new \App\Service\PaieService(($container->privates['App\\Repository\\PaieRepository'] ?? $container->load('getPaieRepositoryService')), ($container->privates['App\\Repository\\PrimeRepository'] ?? $container->load('getPrimeRepositoryService')), ($container->privates['App\\Repository\\HeureSuplementaireRepository'] ?? $container->load('getHeureSuplementaireRepositoryService')), ($container->privates['App\\Repository\\SanctionRepository'] ?? $container->load('getSanctionRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container))), ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService')));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\PaieController', $container));

        return $instance;
    }
}
