<?php

namespace Container0WwmuQl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrimeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.MJNrreu.App\Entity\Prime' shared service.
     *
     * @return \App\Entity\Prime
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.MJNrreu": it needs an instance of "App\\Entity\\Prime" but this type has been excluded in "config/services.yaml".');
    }
}
