<?php

namespace Container0WwmuQl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSoldeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Complement\Solde' shared autowired service.
     *
     * @return \App\Complement\Solde
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Complement'.\DIRECTORY_SEPARATOR.'Solde.php';

        return $container->privates['App\\Complement\\Solde'] = new \App\Complement\Solde();
    }
}
