<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEFrHy7v\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEFrHy7v/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerEFrHy7v.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerEFrHy7v\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerEFrHy7v\App_KernelProdContainer([
    'container.build_hash' => 'EFrHy7v',
    'container.build_id' => '0ebbef84',
    'container.build_time' => 1744641912,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEFrHy7v');
