<?php

namespace ContainerEFrHy7v;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_3hoz_E5Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored.3hoz.E5' shared service.
     *
     * @return \Swift_Mailer
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\Security\\securityController::forgotten()": the $mail argument is type-hinted with the non-existent class or interface: "Swift_Mailer".');
    }
}
