<?php

namespace ContainerEFrHy7v;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_K4Bq10GService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.k4Bq10G' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.k4Bq10G'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'livrerProduitRepository' => ['privates', 'App\\Repository\\LivrerProduitRepository', 'getLivrerProduitRepositoryService', true],
            'reclamation' => ['privates', '.errored..service_locator.k4Bq10G.App\\Entity\\Reclamation', NULL, 'Cannot autowire service ".service_locator.k4Bq10G": it needs an instance of "App\\Entity\\Reclamation" but this type has been excluded in "config/services.yaml".'],
        ], [
            'livrerProduitRepository' => 'App\\Repository\\LivrerProduitRepository',
            'reclamation' => 'App\\Entity\\Reclamation',
        ]);
    }
}
