<?php

namespace ContainerEFrHy7v;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SYGkLDoService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.SYGkLDo' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SYGkLDo'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'primePerformanceRepository' => ['privates', 'App\\Repository\\PrimePerformanceRepository', 'getPrimePerformanceRepositoryService', true],
        ], [
            'primePerformanceRepository' => 'App\\Repository\\PrimePerformanceRepository',
        ]);
    }
}
