<?php

namespace ContainerEFrHy7v;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TZ613IzService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.TZ613Iz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TZ613Iz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'noteServiceRepository' => ['privates', 'App\\Repository\\NoteServiceRepository', 'getNoteServiceRepositoryService', true],
        ], [
            'noteServiceRepository' => 'App\\Repository\\NoteServiceRepository',
        ]);
    }
}
