<?php

namespace ContainerEFrHy7v;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_C8ntkenService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.c8ntken' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.c8ntken'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'absence' => ['privates', '.errored..service_locator.c8ntken.App\\Entity\\Absence', NULL, 'Cannot autowire service ".service_locator.c8ntken": it needs an instance of "App\\Entity\\Absence" but this type has been excluded in "config/services.yaml".'],
        ], [
            'absence' => 'App\\Entity\\Absence',
        ]);
    }
}
