<?php

namespace ContainerEFrHy7v;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2gmBvBoService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.2gmBvBo' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2gmBvBo'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'paieRepository' => ['privates', 'App\\Repository\\PaieRepository', 'getPaieRepositoryService', true],
            'solde' => ['privates', 'App\\Complement\\Solde', 'getSoldeService', true],
        ], [
            'paieRepository' => 'App\\Repository\\PaieRepository',
            'solde' => 'App\\Complement\\Solde',
        ]);
    }
}
