<?php

namespace ContainerEFrHy7v;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PjrYeyBService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.PjrYeyB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.PjrYeyB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'avoir' => ['privates', '.errored..service_locator.PjrYeyB.App\\Entity\\Avoir', NULL, 'Cannot autowire service ".service_locator.PjrYeyB": it needs an instance of "App\\Entity\\Avoir" but this type has been excluded in "config/services.yaml".'],
            'avoirResteRepository' => ['privates', 'App\\Repository\\AvoirResteRepository', 'getAvoirResteRepositoryService', true],
            'solde' => ['privates', 'App\\Complement\\Solde', 'getSoldeService', true],
        ], [
            'avoir' => 'App\\Entity\\Avoir',
            'avoirResteRepository' => 'App\\Repository\\AvoirResteRepository',
            'solde' => 'App\\Complement\\Solde',
        ]);
    }
}
