<?php

namespace ContainerEFrHy7v;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Im1kX7rService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.im1kX7r' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.im1kX7r'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'demandeExplicationRepository' => ['privates', 'App\\Repository\\DemandeExplicationRepository', 'getDemandeExplicationRepositoryService', true],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
        ], [
            'demandeExplicationRepository' => 'App\\Repository\\DemandeExplicationRepository',
            'security' => '?',
        ]);
    }
}
