<?php

namespace ContainerEFrHy7v;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NCXI2AsService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.nCXI2As' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nCXI2As'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'mail' => ['privates', '.errored.3hoz.E5', NULL, 'Cannot determine controller argument for "App\\Controller\\Security\\securityController::forgotten()": the $mail argument is type-hinted with the non-existent class or interface: "Swift_Mailer".'],
            'tokenGenerator' => ['privates', 'security.csrf.token_generator', 'getSecurity_Csrf_TokenGeneratorService', true],
        ], [
            'mail' => '?',
            'tokenGenerator' => '?',
        ]);
    }
}
