<?php

namespace ContainerEFrHy7v;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IXV1LlJService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.IXV1LlJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.IXV1LlJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'heureSuplementaireRepository' => ['privates', 'App\\Repository\\HeureSuplementaireRepository', 'getHeureSuplementaireRepositoryService', true],
            'primeRepository' => ['privates', 'App\\Repository\\PrimeRepository', 'getPrimeRepositoryService', true],
            'retenueRepository' => ['privates', 'App\\Repository\\RetenueRepository', 'getRetenueRepositoryService', true],
        ], [
            'heureSuplementaireRepository' => 'App\\Repository\\HeureSuplementaireRepository',
            'primeRepository' => 'App\\Repository\\PrimeRepository',
            'retenueRepository' => 'App\\Repository\\RetenueRepository',
        ]);
    }
}
