<?php

namespace ContainerEFrHy7v;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RF_GS75Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.rF.gS75' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rF.gS75'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'posteRepository' => ['privates', 'App\\Repository\\PosteRepository', 'getPosteRepositoryService', true],
        ], [
            'posteRepository' => 'App\\Repository\\PosteRepository',
        ]);
    }
}
