<?php

namespace ContainerEFrHy7v;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JI6lAHMService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.JI6lAHM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JI6lAHM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'livrer' => ['privates', '.errored..service_locator.JI6lAHM.App\\Entity\\Livrer', NULL, 'Cannot autowire service ".service_locator.JI6lAHM": it needs an instance of "App\\Entity\\Livrer" but this type has been excluded in "config/services.yaml".'],
        ], [
            'livrer' => 'App\\Entity\\Livrer',
        ]);
    }
}
