<?php

namespace ContainerEFrHy7v;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PPeLVW6Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.PPeLVW6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.PPeLVW6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'encoder' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
            'mail' => ['privates', '.errored.2F.ZoJN', NULL, 'Cannot determine controller argument for "App\\Controller\\Security\\securityController::new()": the $mail argument is type-hinted with the non-existent class or interface: "Swift_Mailer".'],
            'tokenGenerator' => ['privates', 'security.csrf.token_generator', 'getSecurity_Csrf_TokenGeneratorService', true],
        ], [
            'encoder' => '?',
            'mail' => '?',
            'tokenGenerator' => '?',
        ]);
    }
}
