<?php

namespace ContainerEFrHy7v;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CQ8XLGService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.CQ8XLG_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CQ8XLG_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'poste' => ['privates', '.errored..service_locator.CQ8XLG_.App\\Entity\\Poste', NULL, 'Cannot autowire service ".service_locator.CQ8XLG_": it needs an instance of "App\\Entity\\Poste" but this type has been excluded in "config/services.yaml".'],
        ], [
            'poste' => 'App\\Entity\\Poste',
        ]);
    }
}
