<?php

namespace ContainerEFrHy7v;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CaIy2eXService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.caIy2eX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.caIy2eX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'commande' => ['privates', '.errored..service_locator.caIy2eX.App\\Entity\\Commande', NULL, 'Cannot autowire service ".service_locator.caIy2eX": it needs an instance of "App\\Entity\\Commande" but this type has been excluded in "config/services.yaml".'],
            'repository' => ['privates', 'App\\Repository\\LivrerProduitRepository', 'getLivrerProduitRepositoryService', true],
        ], [
            'commande' => 'App\\Entity\\Commande',
            'repository' => 'App\\Repository\\LivrerProduitRepository',
        ]);
    }
}
