<?php

namespace ContainerEFrHy7v;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_F26zfeAService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.f26zfeA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.f26zfeA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'typeCongeRepository' => ['privates', 'App\\Repository\\TypeCongeRepository', 'getTypeCongeRepositoryService', true],
        ], [
            'typeCongeRepository' => 'App\\Repository\\TypeCongeRepository',
        ]);
    }
}
