<?php

namespace ContainerEFrHy7v;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SplMHihService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.SplMHih' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SplMHih'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'avoirRepository' => ['privates', 'App\\Repository\\AvoirRepository', 'getAvoirRepositoryService', true],
        ], [
            'avoirRepository' => 'App\\Repository\\AvoirRepository',
        ]);
    }
}
