<?php

namespace ContainerEFrHy7v;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MJNrreuService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.MJNrreu' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MJNrreu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'prime' => ['privates', '.errored..service_locator.MJNrreu.App\\Entity\\Prime', NULL, 'Cannot autowire service ".service_locator.MJNrreu": it needs an instance of "App\\Entity\\Prime" but this type has been excluded in "config/services.yaml".'],
        ], [
            'prime' => 'App\\Entity\\Prime',
        ]);
    }
}
