<?php

namespace ContainerEFrHy7v;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BembAWsService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.bembAWs' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bembAWs'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'feedback' => ['privates', '.errored..service_locator.bembAWs.App\\Entity\\Feedback', NULL, 'Cannot autowire service ".service_locator.bembAWs": it needs an instance of "App\\Entity\\Feedback" but this type has been excluded in "config/services.yaml".'],
        ], [
            'feedback' => 'App\\Entity\\Feedback',
        ]);
    }
}
