<?php

namespace ContainerEFrHy7v;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5criBkTService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.5criBkT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5criBkT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'typeSanction' => ['privates', '.errored..service_locator.5criBkT.App\\Entity\\TypeSanction', NULL, 'Cannot autowire service ".service_locator.5criBkT": it needs an instance of "App\\Entity\\TypeSanction" but this type has been excluded in "config/services.yaml".'],
        ], [
            'typeSanction' => 'App\\Entity\\TypeSanction',
        ]);
    }
}
