<?php

namespace ContainerEFrHy7v;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ui9XhINService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.Ui9XhIN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Ui9XhIN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repository' => ['privates', 'App\\Repository\\CommandeRepository', 'getCommandeRepositoryService', true],
            'user' => ['privates', '.errored..service_locator.Ui9XhIN.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.Ui9XhIN": it needs an instance of "App\\Entity\\User" but this type has been excluded in "config/services.yaml".'],
        ], [
            'repository' => 'App\\Repository\\CommandeRepository',
            'user' => 'App\\Entity\\User',
        ]);
    }
}
