<?php

namespace ContainerEFrHy7v;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAuthentAuthenticatorService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Security\AuthentAuthenticator' shared autowired service.
     *
     * @return \App\Security\AuthentAuthenticator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Security\\AuthentAuthenticator'] = new \App\Security\AuthentAuthenticator(($container->services['router'] ?? self::getRouterService($container)));
    }
}
