<?php

namespace ContainerEFrHy7v;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBanqueService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.0_IFjR8.App\Entity\Banque' shared service.
     *
     * @return \App\Entity\Banque
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.0_IFjR8": it needs an instance of "App\\Entity\\Banque" but this type has been excluded in "config/services.yaml".');
    }
}
