<?php

namespace ContainerEFrHy7v;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCompteRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\CompteRepository' shared autowired service.
     *
     * @return \App\Repository\CompteRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\CompteRepository'] = new \App\Repository\CompteRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
