<?php

namespace ContainerEFrHy7v;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDepartementService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.EppKkcr.App\Entity\Departement' shared service.
     *
     * @return \App\Entity\Departement
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.EppKkcr": it needs an instance of "App\\Entity\\Departement" but this type has been excluded in "config/services.yaml".');
    }
}
