<?php

namespace ContainerEFrHy7v;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEvaluationType2Service extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\Type\evaluationType' shared autowired service.
     *
     * @return \App\Form\Type\evaluationType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\Type\\evaluationType'] = new \App\Form\Type\evaluationType();
    }
}
