<?php

namespace ContainerEFrHy7v;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEcritureRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\EcritureRepository' shared autowired service.
     *
     * @return \App\Repository\EcritureRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\EcritureRepository'] = new \App\Repository\EcritureRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
