<?php

namespace ContainerEFrHy7v;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHeureSuplementaireTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\HeureSuplementaireType' shared autowired service.
     *
     * @return \App\Form\HeureSuplementaireType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\HeureSuplementaireType'] = new \App\Form\HeureSuplementaireType();
    }
}
