<?php

namespace ContainerEFrHy7v;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLivrerControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\LivrerController' shared autowired service.
     *
     * @return \App\Controller\LivrerController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\LivrerController'] = $instance = new \App\Controller\LivrerController(($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\LivrerController', $container));

        return $instance;
    }
}
