<?php

namespace ContainerEFrHy7v;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPosteService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.CQ8XLG_.App\Entity\Poste' shared service.
     *
     * @return \App\Entity\Poste
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.CQ8XLG_": it needs an instance of "App\\Entity\\Poste" but this type has been excluded in "config/services.yaml".');
    }
}
