<?php

namespace ContainerEFrHy7v;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaieControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\PaieController' shared autowired service.
     *
     * @return \App\Controller\PaieController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\PaieController'] = $instance = new \App\Controller\PaieController(new \App\Service\PaieService(($container->privates['App\\Repository\\PaieRepository'] ?? $container->load('getPaieRepositoryService')), ($container->privates['App\\Repository\\PrimeRepository'] ?? $container->load('getPrimeRepositoryService')), ($container->privates['App\\Repository\\HeureSuplementaireRepository'] ?? $container->load('getHeureSuplementaireRepositoryService')), ($container->privates['App\\Repository\\SanctionRepository'] ?? $container->load('getSanctionRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container))), ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService')));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\PaieController', $container));

        return $instance;
    }
}
