<?php

namespace ContainerEFrHy7v;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrimePerformanceTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\PrimePerformanceType' shared autowired service.
     *
     * @return \App\Form\PrimePerformanceType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\PrimePerformanceType'] = new \App\Form\PrimePerformanceType();
    }
}
