<?php

namespace ContainerEFrHy7v;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRetourService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator..WiOQnA.App\Entity\Retour' shared service.
     *
     * @return \App\Entity\Retour
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator..WiOQnA": it needs an instance of "App\\Entity\\Retour" but this type has been excluded in "config/services.yaml".');
    }
}
