<?php

namespace ContainerEFrHy7v;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSoldeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Complement\Solde' shared autowired service.
     *
     * @return \App\Complement\Solde
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Complement\\Solde'] = new \App\Complement\Solde();
    }
}
