<?php

namespace ContainerEFrHy7v;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSanctionTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\SanctionType' shared autowired service.
     *
     * @return \App\Form\SanctionType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\SanctionType'] = new \App\Form\SanctionType();
    }
}
