<?php

namespace ContainerEFrHy7v;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVerserTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\Type\VerserType' shared autowired service.
     *
     * @return \App\Form\Type\VerserType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\Type\\VerserType'] = new \App\Form\Type\VerserType();
    }
}
