<?php

namespace ContainerSxQMIwT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NkRrMOHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nkRrMOH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nkRrMOH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'livrerProduitRepository' => ['privates', 'App\\Repository\\LivrerProduitRepository', 'getLivrerProduitRepositoryService', true],
            'livrerResteRepository' => ['privates', 'App\\Repository\\LivrerResteRepository', 'getLivrerResteRepositoryService', true],
            'reclamation' => ['privates', '.errored..service_locator.nkRrMOH.App\\Entity\\Reclamation', NULL, 'Cannot autowire service ".service_locator.nkRrMOH": it needs an instance of "App\\Entity\\Reclamation" but this type has been excluded in "config/services.yaml".'],
            'repository' => ['privates', 'App\\Repository\\ProduitRepository', 'getProduitRepositoryService', true],
        ], [
            'livrerProduitRepository' => 'App\\Repository\\LivrerProduitRepository',
            'livrerResteRepository' => 'App\\Repository\\LivrerResteRepository',
            'reclamation' => 'App\\Entity\\Reclamation',
            'repository' => 'App\\Repository\\ProduitRepository',
        ]);
    }
}
