<?php

namespace ContainerSxQMIwT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KJUDKN5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KJUDKN5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KJUDKN5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'approvisionner' => ['privates', '.errored..service_locator.KJUDKN5.App\\Entity\\Approvisionner', NULL, 'Cannot autowire service ".service_locator.KJUDKN5": it needs an instance of "App\\Entity\\Approvisionner" but this type has been excluded in "config/services.yaml".'],
            'repository' => ['privates', 'App\\Repository\\ApprovisionnementRepository', 'getApprovisionnementRepositoryService', true],
        ], [
            'approvisionner' => 'App\\Entity\\Approvisionner',
            'repository' => 'App\\Repository\\ApprovisionnementRepository',
        ]);
    }
}
