<?php

namespace ContainerSxQMIwT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ORb6BpBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ORb6BpB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ORb6BpB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'demandeExplication' => ['privates', '.errored..service_locator.ORb6BpB.App\\Entity\\DemandeExplication', NULL, 'Cannot autowire service ".service_locator.ORb6BpB": it needs an instance of "App\\Entity\\DemandeExplication" but this type has been excluded in "config/services.yaml".'],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
        ], [
            'demandeExplication' => 'App\\Entity\\DemandeExplication',
            'security' => '?',
        ]);
    }
}
