<?php

namespace ContainerSxQMIwT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5CGjU28Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5CGjU28' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5CGjU28'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'approvisionnementRepository' => ['privates', 'App\\Repository\\ApprovisionnementRepository', 'getApprovisionnementRepositoryService', true],
            'approvisionnerRepository' => ['privates', 'App\\Repository\\ApprovisionnerRepository', 'getApprovisionnerRepositoryService', true],
            'avoirRepository' => ['privates', 'App\\Repository\\AvoirRepository', 'getAvoirRepositoryService', true],
            'commandeRepository' => ['privates', 'App\\Repository\\CommandeRepository', 'getCommandeRepositoryService', true],
            'livrerRepository' => ['privates', 'App\\Repository\\LivrerRepository', 'getLivrerRepositoryService', true],
            'produitRepository' => ['privates', 'App\\Repository\\ProduitRepository', 'getProduitRepositoryService', true],
            'promotionRepository' => ['privates', 'App\\Repository\\PromotionRepository', 'getPromotionRepositoryService', true],
            'reclamationRepository' => ['privates', 'App\\Repository\\ReclamationRepository', 'getReclamationRepositoryService', true],
            'repository' => ['privates', 'App\\Repository\\CommandeProduitRepository', 'getCommandeProduitRepositoryService', true],
            'stockRepository' => ['privates', 'App\\Repository\\StockRepository', 'getStockRepositoryService', true],
        ], [
            'approvisionnementRepository' => 'App\\Repository\\ApprovisionnementRepository',
            'approvisionnerRepository' => 'App\\Repository\\ApprovisionnerRepository',
            'avoirRepository' => 'App\\Repository\\AvoirRepository',
            'commandeRepository' => 'App\\Repository\\CommandeRepository',
            'livrerRepository' => 'App\\Repository\\LivrerRepository',
            'produitRepository' => 'App\\Repository\\ProduitRepository',
            'promotionRepository' => 'App\\Repository\\PromotionRepository',
            'reclamationRepository' => 'App\\Repository\\ReclamationRepository',
            'repository' => 'App\\Repository\\CommandeProduitRepository',
            'stockRepository' => 'App\\Repository\\StockRepository',
        ]);
    }
}
