<?php

namespace ContainerSxQMIwT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZKlKQIWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zKlKQIW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zKlKQIW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'avoir' => ['privates', '.errored..service_locator.zKlKQIW.App\\Entity\\Avoir', NULL, 'Cannot autowire service ".service_locator.zKlKQIW": it needs an instance of "App\\Entity\\Avoir" but this type has been excluded in "config/services.yaml".'],
        ], [
            'avoir' => 'App\\Entity\\Avoir',
        ]);
    }
}
