<?php

namespace ContainerSxQMIwT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EppKkcrService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.EppKkcr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.EppKkcr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'departement' => ['privates', '.errored..service_locator.EppKkcr.App\\Entity\\Departement', NULL, 'Cannot autowire service ".service_locator.EppKkcr": it needs an instance of "App\\Entity\\Departement" but this type has been excluded in "config/services.yaml".'],
        ], [
            'departement' => 'App\\Entity\\Departement',
        ]);
    }
}
