<?php

namespace ContainerSxQMIwT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_S67_KI6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.s67.kI6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.s67.kI6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'demandeExplication' => ['privates', '.errored..service_locator.s67.kI6.App\\Entity\\DemandeExplication', NULL, 'Cannot autowire service ".service_locator.s67.kI6": it needs an instance of "App\\Entity\\DemandeExplication" but this type has been excluded in "config/services.yaml".'],
        ], [
            'demandeExplication' => 'App\\Entity\\DemandeExplication',
        ]);
    }
}
