<?php

namespace ContainerSxQMIwT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LJ_UBt7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lJ.UBt7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lJ.UBt7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'message' => ['privates', '.errored..service_locator.lJ.UBt7.App\\Entity\\Message', NULL, 'Cannot autowire service ".service_locator.lJ.UBt7": it needs an instance of "App\\Entity\\Message" but this type has been excluded in "config/services.yaml".'],
        ], [
            'em' => '?',
            'message' => 'App\\Entity\\Message',
        ]);
    }
}
