<?php

namespace ContainerSxQMIwT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GzP66OpService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GzP66Op' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.GzP66Op'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'transfert' => ['privates', '.errored..service_locator.GzP66Op.App\\Entity\\Transfert', NULL, 'Cannot autowire service ".service_locator.GzP66Op": it needs an instance of "App\\Entity\\Transfert" but this type has been excluded in "config/services.yaml".'],
        ], [
            'transfert' => 'App\\Entity\\Transfert',
        ]);
    }
}
