<?php

namespace ContainerSxQMIwT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5Hn467bService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5Hn467b' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5Hn467b'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'commande' => ['privates', '.errored..service_locator.5Hn467b.App\\Entity\\Commande', NULL, 'Cannot autowire service ".service_locator.5Hn467b": it needs an instance of "App\\Entity\\Commande" but this type has been excluded in "config/services.yaml".'],
            'livrerProduitRepository' => ['privates', 'App\\Repository\\LivrerProduitRepository', 'getLivrerProduitRepositoryService', true],
            'livrerRepository' => ['privates', 'App\\Repository\\LivrerRepository', 'getLivrerRepositoryService', true],
            'repository' => ['privates', 'App\\Repository\\ProduitRepository', 'getProduitRepositoryService', true],
        ], [
            'commande' => 'App\\Entity\\Commande',
            'livrerProduitRepository' => 'App\\Repository\\LivrerProduitRepository',
            'livrerRepository' => 'App\\Repository\\LivrerRepository',
            'repository' => 'App\\Repository\\ProduitRepository',
        ]);
    }
}
