<?php

namespace ContainerSxQMIwT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_2F_ZoJNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.2F.ZoJN' shared service.
     *
     * @return \Swift_Mailer
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\Security\\securityController::new()": the $mail argument is type-hinted with the non-existent class or interface: "Swift_Mailer".');
    }
}
