<?php

namespace ContainerSxQMIwT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Wn0oHAnService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Wn0oHAn' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Wn0oHAn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'typeContratRepository' => ['privates', 'App\\Repository\\TypeContratRepository', 'getTypeContratRepositoryService', true],
        ], [
            'typeContratRepository' => 'App\\Repository\\TypeContratRepository',
        ]);
    }
}
