<?php

namespace ContainerSxQMIwT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0IFjR8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0_IFjR8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0_IFjR8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'banque' => ['privates', '.errored..service_locator.0_IFjR8.App\\Entity\\Banque', NULL, 'Cannot autowire service ".service_locator.0_IFjR8": it needs an instance of "App\\Entity\\Banque" but this type has been excluded in "config/services.yaml".'],
        ], [
            'banque' => 'App\\Entity\\Banque',
        ]);
    }
}
