<?php

namespace ContainerSxQMIwT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NwITGr8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nwITGr8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nwITGr8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'critereEvaluationRepository' => ['privates', 'App\\Repository\\CritereEvaluationRepository', 'getCritereEvaluationRepositoryService', true],
        ], [
            'critereEvaluationRepository' => 'App\\Repository\\CritereEvaluationRepository',
        ]);
    }
}
