<?php

namespace ContainerSxQMIwT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HYKOxsGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hYKOxsG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hYKOxsG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'livrerRepository' => ['privates', 'App\\Repository\\LivrerRepository', 'getLivrerRepositoryService', true],
            'repository' => ['privates', 'App\\Repository\\CommandeRepository', 'getCommandeRepositoryService', true],
            'retourProduitRepository' => ['privates', 'App\\Repository\\RetourProduitRepository', 'getRetourProduitRepositoryService', true],
        ], [
            'livrerRepository' => 'App\\Repository\\LivrerRepository',
            'repository' => 'App\\Repository\\CommandeRepository',
            'retourProduitRepository' => 'App\\Repository\\RetourProduitRepository',
        ]);
    }
}
