<?php

namespace ContainerSxQMIwT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5X2ZcxVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5X2ZcxV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5X2ZcxV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'financement' => ['privates', '.errored..service_locator.5X2ZcxV.App\\Entity\\Financement', NULL, 'Cannot autowire service ".service_locator.5X2ZcxV": it needs an instance of "App\\Entity\\Financement" but this type has been excluded in "config/services.yaml".'],
        ], [
            'financement' => 'App\\Entity\\Financement',
        ]);
    }
}
