<?php

namespace ContainerSxQMIwT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IHHwidkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iHHwidk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iHHwidk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'banque' => ['privates', '.errored..service_locator.iHHwidk.App\\Entity\\Banque', NULL, 'Cannot autowire service ".service_locator.iHHwidk": it needs an instance of "App\\Entity\\Banque" but this type has been excluded in "config/services.yaml".'],
            'repository' => ['privates', 'App\\Repository\\EcritureRepository', 'getEcritureRepositoryService', true],
            'solde' => ['privates', 'App\\Complement\\Solde', 'getSoldeService', true],
        ], [
            'banque' => 'App\\Entity\\Banque',
            'repository' => 'App\\Repository\\EcritureRepository',
            'solde' => 'App\\Complement\\Solde',
        ]);
    }
}
