<?php

namespace ContainerSxQMIwT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FDTLJwWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fDTLJwW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fDTLJwW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'noteService' => ['privates', '.errored..service_locator.fDTLJwW.App\\Entity\\NoteService', NULL, 'Cannot autowire service ".service_locator.fDTLJwW": it needs an instance of "App\\Entity\\NoteService" but this type has been excluded in "config/services.yaml".'],
        ], [
            'noteService' => 'App\\Entity\\NoteService',
        ]);
    }
}
