<?php

namespace ContainerSxQMIwT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Mol62a_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mol62a.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mol62a.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'heureSuplementaire' => ['privates', '.errored..service_locator.mol62a..App\\Entity\\HeureSuplementaire', NULL, 'Cannot autowire service ".service_locator.mol62a.": it needs an instance of "App\\Entity\\HeureSuplementaire" but this type has been excluded in "config/services.yaml".'],
        ], [
            'heureSuplementaire' => 'App\\Entity\\HeureSuplementaire',
        ]);
    }
}
