<?php

namespace ContainerSxQMIwT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GJFCC1VService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GJFCC1V' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.GJFCC1V'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'encoder' => ['privates', '.errored.QbcOcOy', NULL, 'Cannot determine controller argument for "App\\Controller\\Security\\securityController::reset()": the $encoder argument is type-hinted with the non-existent class or interface: "App\\Controller\\Security\\UserPasswordEncoderInterface". Did you forget to add a use statement?'],
        ], [
            'encoder' => '?',
        ]);
    }
}
