<?php

namespace ContainerSxQMIwT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAbsence2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.c8ntken.App\Entity\Absence' shared service.
     *
     * @return \App\Entity\Absence
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.c8ntken": it needs an instance of "App\\Entity\\Absence" but this type has been excluded in "config/services.yaml".');
    }
}
