<?php

namespace ContainerSxQMIwT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCongesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.L9F73kI.App\Entity\Conges' shared service.
     *
     * @return \App\Entity\Conges
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.L9F73kI": it needs an instance of "App\\Entity\\Conges" but this type has been excluded in "config/services.yaml".');
    }
}
