<?php

namespace ContainerSxQMIwT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDemandeExplication3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.s67.kI6.App\Entity\DemandeExplication' shared service.
     *
     * @return \App\Entity\DemandeExplication
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.s67.kI6": it needs an instance of "App\\Entity\\DemandeExplication" but this type has been excluded in "config/services.yaml".');
    }
}
