<?php

namespace ContainerSxQMIwT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRetour2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.0FQRyqG.App\Entity\Retour' shared service.
     *
     * @return \App\Entity\Retour
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.0FQRyqG": it needs an instance of "App\\Entity\\Retour" but this type has been excluded in "config/services.yaml".');
    }
}
