<?php

namespace ContainerSxQMIwT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSanctionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.FvaKkR4.App\Entity\Sanction' shared service.
     *
     * @return \App\Entity\Sanction
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.FvaKkR4": it needs an instance of "App\\Entity\\Sanction" but this type has been excluded in "config/services.yaml".');
    }
}
