<?php

namespace ContainerSxQMIwT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTypeContratService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.s6oL59b.App\Entity\TypeContrat' shared service.
     *
     * @return \App\Entity\TypeContrat
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.s6oL59b": it needs an instance of "App\\Entity\\TypeContrat" but this type has been excluded in "config/services.yaml".');
    }
}
