<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSxQMIwT\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSxQMIwT/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSxQMIwT.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSxQMIwT\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSxQMIwT\App_KernelDevDebugContainer([
    'container.build_hash' => 'SxQMIwT',
    'container.build_id' => '96a3c2ab',
    'container.build_time' => 1744661554,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSxQMIwT');
