<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Produit extends \App\Entity\Produit implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'adresse' => [parent::class, 'adresse', null, 16],
        "\0".parent::class."\0".'commandeProduits' => [parent::class, 'commandeProduits', null, 16],
        "\0".parent::class."\0".'creation' => [parent::class, 'creation', null, 16],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null, 16],
        "\0".parent::class."\0".'desigantion' => [parent::class, 'desigantion', null, 16],
        "\0".parent::class."\0".'fabriquant' => [parent::class, 'fabriquant', null, 16],
        "\0".parent::class."\0".'fournisseurs' => [parent::class, 'fournisseurs', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'lot' => [parent::class, 'lot', null, 16],
        "\0".parent::class."\0".'mincommande' => [parent::class, 'mincommande', null, 16],
        "\0".parent::class."\0".'peremption' => [parent::class, 'peremption', null, 16],
        "\0".parent::class."\0".'pght' => [parent::class, 'pght', null, 16],
        "\0".parent::class."\0".'prix' => [parent::class, 'prix', null, 16],
        "\0".parent::class."\0".'prixpublic' => [parent::class, 'prixpublic', null, 16],
        "\0".parent::class."\0".'promotion' => [parent::class, 'promotion', null, 16],
        "\0".parent::class."\0".'promotionProduits' => [parent::class, 'promotionProduits', null, 16],
        "\0".parent::class."\0".'quantite' => [parent::class, 'quantite', null, 16],
        "\0".parent::class."\0".'reference' => [parent::class, 'reference', null, 16],
        "\0".parent::class."\0".'stock' => [parent::class, 'stock', null, 16],
        "\0".parent::class."\0".'telephone' => [parent::class, 'telephone', null, 16],
        "\0".parent::class."\0".'tva' => [parent::class, 'tva', null, 16],
        'adresse' => [parent::class, 'adresse', null, 16],
        'commandeProduits' => [parent::class, 'commandeProduits', null, 16],
        'creation' => [parent::class, 'creation', null, 16],
        'description' => [parent::class, 'description', null, 16],
        'desigantion' => [parent::class, 'desigantion', null, 16],
        'fabriquant' => [parent::class, 'fabriquant', null, 16],
        'fournisseurs' => [parent::class, 'fournisseurs', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'lot' => [parent::class, 'lot', null, 16],
        'mincommande' => [parent::class, 'mincommande', null, 16],
        'peremption' => [parent::class, 'peremption', null, 16],
        'pght' => [parent::class, 'pght', null, 16],
        'prix' => [parent::class, 'prix', null, 16],
        'prixpublic' => [parent::class, 'prixpublic', null, 16],
        'promotion' => [parent::class, 'promotion', null, 16],
        'promotionProduits' => [parent::class, 'promotionProduits', null, 16],
        'quantite' => [parent::class, 'quantite', null, 16],
        'reference' => [parent::class, 'reference', null, 16],
        'stock' => [parent::class, 'stock', null, 16],
        'telephone' => [parent::class, 'telephone', null, 16],
        'tva' => [parent::class, 'tva', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
