<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CommandeProduit extends \App\Entity\CommandeProduit implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'commande' => [parent::class, 'commande', null, 16],
        "\0".parent::class."\0".'date' => [parent::class, 'date', null, 16],
        "\0".parent::class."\0".'produit' => [parent::class, 'produit', null, 16],
        "\0".parent::class."\0".'promotion' => [parent::class, 'promotion', null, 16],
        "\0".parent::class."\0".'publique' => [parent::class, 'publique', null, 16],
        "\0".parent::class."\0".'quantite' => [parent::class, 'quantite', null, 16],
        "\0".parent::class."\0".'session' => [parent::class, 'session', null, 16],
        "\0".parent::class."\0".'stock' => [parent::class, 'stock', null, 16],
        "\0".parent::class."\0".'tva' => [parent::class, 'tva', null, 16],
        'commande' => [parent::class, 'commande', null, 16],
        'date' => [parent::class, 'date', null, 16],
        'produit' => [parent::class, 'produit', null, 16],
        'promotion' => [parent::class, 'promotion', null, 16],
        'publique' => [parent::class, 'publique', null, 16],
        'quantite' => [parent::class, 'quantite', null, 16],
        'session' => [parent::class, 'session', null, 16],
        'stock' => [parent::class, 'stock', null, 16],
        'tva' => [parent::class, 'tva', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
