<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ReponseExplication extends \App\Entity\ReponseExplication implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'dateReponse' => [parent::class, 'dateReponse', null, 16],
        "\0".parent::class."\0".'demande' => [parent::class, 'demande', null, 16],
        "\0".parent::class."\0".'employe' => [parent::class, 'employe', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'objet' => [parent::class, 'objet', null, 16],
        "\0".parent::class."\0".'reponse' => [parent::class, 'reponse', null, 16],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null, 16],
        'dateReponse' => [parent::class, 'dateReponse', null, 16],
        'demande' => [parent::class, 'demande', null, 16],
        'employe' => [parent::class, 'employe', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'objet' => [parent::class, 'objet', null, 16],
        'reponse' => [parent::class, 'reponse', null, 16],
        'status' => [parent::class, 'status', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
