<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Entity\User implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".'*'."\0".'roles' => [parent::class, 'roles', null, 8],
        "\0".parent::class."\0".'adresse' => [parent::class, 'adresse', null, 16],
        "\0".parent::class."\0".'client' => [parent::class, 'client', null, 16],
        "\0".parent::class."\0".'depenses' => [parent::class, 'depenses', null, 16],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null, 16],
        "\0".parent::class."\0".'enabled' => [parent::class, 'enabled', null, 16],
        "\0".parent::class."\0".'fonction' => [parent::class, 'fonction', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'livreur' => [parent::class, 'livreur', null, 16],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null, 16],
        "\0".parent::class."\0".'password' => [parent::class, 'password', null, 16],
        "\0".parent::class."\0".'phone' => [parent::class, 'phone', null, 16],
        "\0".parent::class."\0".'prenom' => [parent::class, 'prenom', null, 16],
        "\0".parent::class."\0".'received' => [parent::class, 'received', null, 16],
        "\0".parent::class."\0".'resetToken' => [parent::class, 'resetToken', null, 16],
        "\0".parent::class."\0".'sent' => [parent::class, 'sent', null, 16],
        "\0".parent::class."\0".'transferts' => [parent::class, 'transferts', null, 16],
        "\0".parent::class."\0".'username' => [parent::class, 'username', null, 16],
        'adresse' => [parent::class, 'adresse', null, 16],
        'client' => [parent::class, 'client', null, 16],
        'confirm' => [parent::class, 'confirm', null, 4],
        'depenses' => [parent::class, 'depenses', null, 16],
        'email' => [parent::class, 'email', null, 16],
        'enabled' => [parent::class, 'enabled', null, 16],
        'fonction' => [parent::class, 'fonction', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'livreur' => [parent::class, 'livreur', null, 16],
        'nom' => [parent::class, 'nom', null, 16],
        'password' => [parent::class, 'password', null, 16],
        'phone' => [parent::class, 'phone', null, 16],
        'prenom' => [parent::class, 'prenom', null, 16],
        'received' => [parent::class, 'received', null, 16],
        'resetToken' => [parent::class, 'resetToken', null, 16],
        'roles' => [parent::class, 'roles', null, 8],
        'sent' => [parent::class, 'sent', null, 16],
        'test' => [parent::class, 'test', null, 4],
        'transferts' => [parent::class, 'transferts', null, 16],
        'username' => [parent::class, 'username', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
