<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Financement extends \App\Entity\Financement implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'Type' => [parent::class, 'Type', null, 16],
        "\0".parent::class."\0".'apport' => [parent::class, 'apport', null, 16],
        "\0".parent::class."\0".'banque' => [parent::class, 'banque', null, 16],
        "\0".parent::class."\0".'compte' => [parent::class, 'compte', null, 16],
        "\0".parent::class."\0".'compteinteret' => [parent::class, 'compteinteret', null, 16],
        "\0".parent::class."\0".'date' => [parent::class, 'date', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'libellecompte' => [parent::class, 'libellecompte', null, 16],
        "\0".parent::class."\0".'montant' => [parent::class, 'montant', null, 16],
        "\0".parent::class."\0".'motif' => [parent::class, 'motif', null, 16],
        "\0".parent::class."\0".'numero' => [parent::class, 'numero', null, 16],
        "\0".parent::class."\0".'remboursements' => [parent::class, 'remboursements', null, 16],
        "\0".parent::class."\0".'taux' => [parent::class, 'taux', null, 16],
        'Type' => [parent::class, 'Type', null, 16],
        'apport' => [parent::class, 'apport', null, 16],
        'banque' => [parent::class, 'banque', null, 16],
        'compte' => [parent::class, 'compte', null, 16],
        'compteinteret' => [parent::class, 'compteinteret', null, 16],
        'date' => [parent::class, 'date', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'libellecompte' => [parent::class, 'libellecompte', null, 16],
        'montant' => [parent::class, 'montant', null, 16],
        'motif' => [parent::class, 'motif', null, 16],
        'numero' => [parent::class, 'numero', null, 16],
        'remboursements' => [parent::class, 'remboursements', null, 16],
        'taux' => [parent::class, 'taux', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
