<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Ecriture extends \App\Entity\Ecriture implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'comptecredit' => [parent::class, 'comptecredit', null, 16],
        "\0".parent::class."\0".'comptedebit' => [parent::class, 'comptedebit', null, 16],
        "\0".parent::class."\0".'credit' => [parent::class, 'credit', null, 16],
        "\0".parent::class."\0".'date' => [parent::class, 'date', null, 16],
        "\0".parent::class."\0".'debit' => [parent::class, 'debit', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'libelle' => [parent::class, 'libelle', null, 16],
        "\0".parent::class."\0".'libellecomptecredit' => [parent::class, 'libellecomptecredit', null, 16],
        "\0".parent::class."\0".'libellecomptedebit' => [parent::class, 'libellecomptedebit', null, 16],
        "\0".parent::class."\0".'montant' => [parent::class, 'montant', null, 16],
        "\0".parent::class."\0".'solde' => [parent::class, 'solde', null, 16],
        "\0".parent::class."\0".'type' => [parent::class, 'type', null, 16],
        'comptecredit' => [parent::class, 'comptecredit', null, 16],
        'comptedebit' => [parent::class, 'comptedebit', null, 16],
        'credit' => [parent::class, 'credit', null, 16],
        'date' => [parent::class, 'date', null, 16],
        'debit' => [parent::class, 'debit', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'libelle' => [parent::class, 'libelle', null, 16],
        'libellecomptecredit' => [parent::class, 'libellecomptecredit', null, 16],
        'libellecomptedebit' => [parent::class, 'libellecomptedebit', null, 16],
        'montant' => [parent::class, 'montant', null, 16],
        'solde' => [parent::class, 'solde', null, 16],
        'type' => [parent::class, 'type', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
