<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Evaluation extends \App\Entity\Evaluation implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'critereEvaluation' => [parent::class, 'critereEvaluation', null, 16],
        "\0".parent::class."\0".'dateEvaluation' => [parent::class, 'dateEvaluation', null, 16],
        "\0".parent::class."\0".'employe' => [parent::class, 'employe', null, 16],
        "\0".parent::class."\0".'evaluationDetails' => [parent::class, 'evaluationDetails', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'moyenne' => [parent::class, 'moyenne', null, 16],
        'critereEvaluation' => [parent::class, 'critereEvaluation', null, 16],
        'dateEvaluation' => [parent::class, 'dateEvaluation', null, 16],
        'employe' => [parent::class, 'employe', null, 16],
        'evaluationDetails' => [parent::class, 'evaluationDetails', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'moyenne' => [parent::class, 'moyenne', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
