<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Formation extends \App\Entity\Formation implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'contenu' => [parent::class, 'contenu', null, 16],
        "\0".parent::class."\0".'datedebut' => [parent::class, 'datedebut', null, 16],
        "\0".parent::class."\0".'datefin' => [parent::class, 'datefin', null, 16],
        "\0".parent::class."\0".'employe' => [parent::class, 'employe', null, 16],
        "\0".parent::class."\0".'employeFormations' => [parent::class, 'employeFormations', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'lieu' => [parent::class, 'lieu', null, 16],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null, 16],
        "\0".parent::class."\0".'type' => [parent::class, 'type', null, 16],
        'contenu' => [parent::class, 'contenu', null, 16],
        'datedebut' => [parent::class, 'datedebut', null, 16],
        'datefin' => [parent::class, 'datefin', null, 16],
        'employe' => [parent::class, 'employe', null, 16],
        'employeFormations' => [parent::class, 'employeFormations', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'lieu' => [parent::class, 'lieu', null, 16],
        'nom' => [parent::class, 'nom', null, 16],
        'type' => [parent::class, 'type', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
