<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Client extends \App\Entity\Client implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".'*'."\0".'roles' => [parent::class, 'roles', null, 8],
        "\0".parent::class."\0".'compte' => [parent::class, 'compte', null, 16],
        "\0".'App\\Entity\\User'."\0".'adresse' => ['App\\Entity\\User', 'adresse', null, 16],
        "\0".'App\\Entity\\User'."\0".'client' => ['App\\Entity\\User', 'client', null, 16],
        "\0".'App\\Entity\\User'."\0".'depenses' => ['App\\Entity\\User', 'depenses', null, 16],
        "\0".'App\\Entity\\User'."\0".'email' => ['App\\Entity\\User', 'email', null, 16],
        "\0".'App\\Entity\\User'."\0".'enabled' => ['App\\Entity\\User', 'enabled', null, 16],
        "\0".'App\\Entity\\User'."\0".'fonction' => ['App\\Entity\\User', 'fonction', null, 16],
        "\0".'App\\Entity\\User'."\0".'id' => ['App\\Entity\\User', 'id', null, 16],
        "\0".'App\\Entity\\User'."\0".'livreur' => ['App\\Entity\\User', 'livreur', null, 16],
        "\0".'App\\Entity\\User'."\0".'nom' => ['App\\Entity\\User', 'nom', null, 16],
        "\0".'App\\Entity\\User'."\0".'password' => ['App\\Entity\\User', 'password', null, 16],
        "\0".'App\\Entity\\User'."\0".'phone' => ['App\\Entity\\User', 'phone', null, 16],
        "\0".'App\\Entity\\User'."\0".'prenom' => ['App\\Entity\\User', 'prenom', null, 16],
        "\0".'App\\Entity\\User'."\0".'received' => ['App\\Entity\\User', 'received', null, 16],
        "\0".'App\\Entity\\User'."\0".'resetToken' => ['App\\Entity\\User', 'resetToken', null, 16],
        "\0".'App\\Entity\\User'."\0".'sent' => ['App\\Entity\\User', 'sent', null, 16],
        "\0".'App\\Entity\\User'."\0".'transferts' => ['App\\Entity\\User', 'transferts', null, 16],
        "\0".'App\\Entity\\User'."\0".'username' => ['App\\Entity\\User', 'username', null, 16],
        'adresse' => ['App\\Entity\\User', 'adresse', null, 16],
        'client' => ['App\\Entity\\User', 'client', null, 16],
        'compte' => [parent::class, 'compte', null, 16],
        'confirm' => [parent::class, 'confirm', null, 4],
        'depenses' => ['App\\Entity\\User', 'depenses', null, 16],
        'email' => ['App\\Entity\\User', 'email', null, 16],
        'enabled' => ['App\\Entity\\User', 'enabled', null, 16],
        'fonction' => ['App\\Entity\\User', 'fonction', null, 16],
        'id' => ['App\\Entity\\User', 'id', null, 16],
        'livreur' => ['App\\Entity\\User', 'livreur', null, 16],
        'nom' => ['App\\Entity\\User', 'nom', null, 16],
        'password' => ['App\\Entity\\User', 'password', null, 16],
        'phone' => ['App\\Entity\\User', 'phone', null, 16],
        'prenom' => ['App\\Entity\\User', 'prenom', null, 16],
        'received' => ['App\\Entity\\User', 'received', null, 16],
        'resetToken' => ['App\\Entity\\User', 'resetToken', null, 16],
        'roles' => [parent::class, 'roles', null, 8],
        'sent' => ['App\\Entity\\User', 'sent', null, 16],
        'test' => [parent::class, 'test', null, 4],
        'transferts' => ['App\\Entity\\User', 'transferts', null, 16],
        'username' => ['App\\Entity\\User', 'username', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
