<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Avoir extends \App\Entity\Avoir implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'Montant' => [parent::class, 'Montant', null, 16],
        "\0".parent::class."\0".'admin' => [parent::class, 'admin', null, 16],
        "\0".parent::class."\0".'client' => [parent::class, 'client', null, 16],
        "\0".parent::class."\0".'commande' => [parent::class, 'commande', null, 16],
        "\0".parent::class."\0".'date' => [parent::class, 'date', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'rebourser' => [parent::class, 'rebourser', null, 16],
        "\0".parent::class."\0".'reclamation' => [parent::class, 'reclamation', null, 16],
        "\0".parent::class."\0".'remboursement' => [parent::class, 'remboursement', null, 16],
        "\0".parent::class."\0".'reste' => [parent::class, 'reste', null, 16],
        "\0".parent::class."\0".'retour' => [parent::class, 'retour', null, 16],
        'Montant' => [parent::class, 'Montant', null, 16],
        'admin' => [parent::class, 'admin', null, 16],
        'client' => [parent::class, 'client', null, 16],
        'commande' => [parent::class, 'commande', null, 16],
        'date' => [parent::class, 'date', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'rebourser' => [parent::class, 'rebourser', null, 16],
        'reclamation' => [parent::class, 'reclamation', null, 16],
        'remboursement' => [parent::class, 'remboursement', null, 16],
        'reste' => [parent::class, 'reste', null, 16],
        'retour' => [parent::class, 'retour', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
