<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Promotion extends \App\Entity\Promotion implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'cinquieme' => [parent::class, 'cinquieme', null, 16],
        "\0".parent::class."\0".'debut' => [parent::class, 'debut', null, 16],
        "\0".parent::class."\0".'designation' => [parent::class, 'designation', null, 16],
        "\0".parent::class."\0".'deuxieme' => [parent::class, 'deuxieme', null, 16],
        "\0".parent::class."\0".'fin' => [parent::class, 'fin', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'premier' => [parent::class, 'premier', null, 16],
        "\0".parent::class."\0".'promotionProduits' => [parent::class, 'promotionProduits', null, 16],
        "\0".parent::class."\0".'quatrieme' => [parent::class, 'quatrieme', null, 16],
        "\0".parent::class."\0".'reduction' => [parent::class, 'reduction', null, 16],
        "\0".parent::class."\0".'troisieme' => [parent::class, 'troisieme', null, 16],
        "\0".parent::class."\0".'type' => [parent::class, 'type', null, 16],
        "\0".parent::class."\0".'ugcinquieme' => [parent::class, 'ugcinquieme', null, 16],
        "\0".parent::class."\0".'ugdeuxieme' => [parent::class, 'ugdeuxieme', null, 16],
        "\0".parent::class."\0".'ugpremier' => [parent::class, 'ugpremier', null, 16],
        "\0".parent::class."\0".'ugquatrieme' => [parent::class, 'ugquatrieme', null, 16],
        "\0".parent::class."\0".'ugtroisieme' => [parent::class, 'ugtroisieme', null, 16],
        "\0".parent::class."\0".'user' => [parent::class, 'user', null, 16],
        'cinquieme' => [parent::class, 'cinquieme', null, 16],
        'debut' => [parent::class, 'debut', null, 16],
        'designation' => [parent::class, 'designation', null, 16],
        'deuxieme' => [parent::class, 'deuxieme', null, 16],
        'fin' => [parent::class, 'fin', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'premier' => [parent::class, 'premier', null, 16],
        'promotionProduits' => [parent::class, 'promotionProduits', null, 16],
        'quatrieme' => [parent::class, 'quatrieme', null, 16],
        'reduction' => [parent::class, 'reduction', null, 16],
        'troisieme' => [parent::class, 'troisieme', null, 16],
        'type' => [parent::class, 'type', null, 16],
        'ugcinquieme' => [parent::class, 'ugcinquieme', null, 16],
        'ugdeuxieme' => [parent::class, 'ugdeuxieme', null, 16],
        'ugpremier' => [parent::class, 'ugpremier', null, 16],
        'ugquatrieme' => [parent::class, 'ugquatrieme', null, 16],
        'ugtroisieme' => [parent::class, 'ugtroisieme', null, 16],
        'user' => [parent::class, 'user', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
