<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Credit extends \App\Entity\Credit implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'compte' => [parent::class, 'compte', null, 16],
        "\0".parent::class."\0".'date' => [parent::class, 'date', null, 16],
        "\0".parent::class."\0".'financement' => [parent::class, 'financement', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'montant' => [parent::class, 'montant', null, 16],
        "\0".parent::class."\0".'paiement' => [parent::class, 'paiement', null, 16],
        "\0".parent::class."\0".'transfert' => [parent::class, 'transfert', null, 16],
        "\0".parent::class."\0".'tva' => [parent::class, 'tva', null, 16],
        "\0".parent::class."\0".'type' => [parent::class, 'type', null, 16],
        "\0".parent::class."\0".'versement' => [parent::class, 'versement', null, 16],
        'compte' => [parent::class, 'compte', null, 16],
        'date' => [parent::class, 'date', null, 16],
        'financement' => [parent::class, 'financement', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'montant' => [parent::class, 'montant', null, 16],
        'paiement' => [parent::class, 'paiement', null, 16],
        'transfert' => [parent::class, 'transfert', null, 16],
        'tva' => [parent::class, 'tva', null, 16],
        'type' => [parent::class, 'type', null, 16],
        'versement' => [parent::class, 'versement', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
