<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Employe extends \App\Entity\Employe implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".'*'."\0".'roles' => [parent::class, 'roles', null, 8],
        "\0".parent::class."\0".'NombreJoursConges' => [parent::class, 'NombreJoursConges', null, 16],
        "\0".parent::class."\0".'absence' => [parent::class, 'absence', null, 16],
        "\0".parent::class."\0".'absences' => [parent::class, 'absences', null, 16],
        "\0".parent::class."\0".'bloodgroup' => [parent::class, 'bloodgroup', null, 16],
        "\0".parent::class."\0".'calendriers' => [parent::class, 'calendriers', null, 16],
        "\0".parent::class."\0".'civilite' => [parent::class, 'civilite', null, 16],
        "\0".parent::class."\0".'conges' => [parent::class, 'conges', null, 16],
        "\0".parent::class."\0".'contrat' => [parent::class, 'contrat', null, 16],
        "\0".parent::class."\0".'dateNaissance' => [parent::class, 'dateNaissance', null, 16],
        "\0".parent::class."\0".'decisions' => [parent::class, 'decisions', null, 16],
        "\0".parent::class."\0".'demandeExplication' => [parent::class, 'demandeExplication', null, 16],
        "\0".parent::class."\0".'demandeExplications' => [parent::class, 'demandeExplications', null, 16],
        "\0".parent::class."\0".'diabete' => [parent::class, 'diabete', null, 16],
        "\0".parent::class."\0".'documents' => [parent::class, 'documents', null, 16],
        "\0".parent::class."\0".'employeFormations' => [parent::class, 'employeFormations', null, 16],
        "\0".parent::class."\0".'enfant' => [parent::class, 'enfant', null, 16],
        "\0".parent::class."\0".'epilepsie' => [parent::class, 'epilepsie', null, 16],
        "\0".parent::class."\0".'evaluations' => [parent::class, 'evaluations', null, 16],
        "\0".parent::class."\0".'famillylink' => [parent::class, 'famillylink', null, 16],
        "\0".parent::class."\0".'famillyname' => [parent::class, 'famillyname', null, 16],
        "\0".parent::class."\0".'famillyphone' => [parent::class, 'famillyphone', null, 16],
        "\0".parent::class."\0".'feedback' => [parent::class, 'feedback', null, 16],
        "\0".parent::class."\0".'formations' => [parent::class, 'formations', null, 16],
        "\0".parent::class."\0".'handicap' => [parent::class, 'handicap', null, 16],
        "\0".parent::class."\0".'heureSuplementaires' => [parent::class, 'heureSuplementaires', null, 16],
        "\0".parent::class."\0".'hireDate' => [parent::class, 'hireDate', null, 16],
        "\0".parent::class."\0".'hyper' => [parent::class, 'hyper', null, 16],
        "\0".parent::class."\0".'hypo' => [parent::class, 'hypo', null, 16],
        "\0".parent::class."\0".'lieuNaissance' => [parent::class, 'lieuNaissance', null, 16],
        "\0".parent::class."\0".'matricule' => [parent::class, 'matricule', null, 16],
        "\0".parent::class."\0".'messageReplies' => [parent::class, 'messageReplies', null, 16],
        "\0".parent::class."\0".'nationalite' => [parent::class, 'nationalite', null, 16],
        "\0".parent::class."\0".'noteService' => [parent::class, 'noteService', null, 16],
        "\0".parent::class."\0".'noteServices' => [parent::class, 'noteServices', null, 16],
        "\0".parent::class."\0".'notifications' => [parent::class, 'notifications', null, 16],
        "\0".parent::class."\0".'paieSalaires' => [parent::class, 'paieSalaires', null, 16],
        "\0".parent::class."\0".'paies' => [parent::class, 'paies', null, 16],
        "\0".parent::class."\0".'poste' => [parent::class, 'poste', null, 16],
        "\0".parent::class."\0".'posteEmployes' => [parent::class, 'posteEmployes', null, 16],
        "\0".parent::class."\0".'primePerformances' => [parent::class, 'primePerformances', null, 16],
        "\0".parent::class."\0".'primes' => [parent::class, 'primes', null, 16],
        "\0".parent::class."\0".'remark' => [parent::class, 'remark', null, 16],
        "\0".parent::class."\0".'reponseExplications' => [parent::class, 'reponseExplications', null, 16],
        "\0".parent::class."\0".'retenues' => [parent::class, 'retenues', null, 16],
        "\0".parent::class."\0".'sanctions' => [parent::class, 'sanctions', null, 16],
        "\0".parent::class."\0".'sexe' => [parent::class, 'sexe', null, 16],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null, 16],
        "\0".'App\\Entity\\User'."\0".'adresse' => ['App\\Entity\\User', 'adresse', null, 16],
        "\0".'App\\Entity\\User'."\0".'client' => ['App\\Entity\\User', 'client', null, 16],
        "\0".'App\\Entity\\User'."\0".'depenses' => ['App\\Entity\\User', 'depenses', null, 16],
        "\0".'App\\Entity\\User'."\0".'email' => ['App\\Entity\\User', 'email', null, 16],
        "\0".'App\\Entity\\User'."\0".'enabled' => ['App\\Entity\\User', 'enabled', null, 16],
        "\0".'App\\Entity\\User'."\0".'fonction' => ['App\\Entity\\User', 'fonction', null, 16],
        "\0".'App\\Entity\\User'."\0".'id' => ['App\\Entity\\User', 'id', null, 16],
        "\0".'App\\Entity\\User'."\0".'livreur' => ['App\\Entity\\User', 'livreur', null, 16],
        "\0".'App\\Entity\\User'."\0".'nom' => ['App\\Entity\\User', 'nom', null, 16],
        "\0".'App\\Entity\\User'."\0".'password' => ['App\\Entity\\User', 'password', null, 16],
        "\0".'App\\Entity\\User'."\0".'phone' => ['App\\Entity\\User', 'phone', null, 16],
        "\0".'App\\Entity\\User'."\0".'prenom' => ['App\\Entity\\User', 'prenom', null, 16],
        "\0".'App\\Entity\\User'."\0".'received' => ['App\\Entity\\User', 'received', null, 16],
        "\0".'App\\Entity\\User'."\0".'resetToken' => ['App\\Entity\\User', 'resetToken', null, 16],
        "\0".'App\\Entity\\User'."\0".'sent' => ['App\\Entity\\User', 'sent', null, 16],
        "\0".'App\\Entity\\User'."\0".'transferts' => ['App\\Entity\\User', 'transferts', null, 16],
        "\0".'App\\Entity\\User'."\0".'username' => ['App\\Entity\\User', 'username', null, 16],
        'NombreJoursConges' => [parent::class, 'NombreJoursConges', null, 16],
        'absence' => [parent::class, 'absence', null, 16],
        'absences' => [parent::class, 'absences', null, 16],
        'adresse' => ['App\\Entity\\User', 'adresse', null, 16],
        'bloodgroup' => [parent::class, 'bloodgroup', null, 16],
        'calendriers' => [parent::class, 'calendriers', null, 16],
        'civilite' => [parent::class, 'civilite', null, 16],
        'client' => ['App\\Entity\\User', 'client', null, 16],
        'confirm' => [parent::class, 'confirm', null, 4],
        'conges' => [parent::class, 'conges', null, 16],
        'contrat' => [parent::class, 'contrat', null, 16],
        'dateNaissance' => [parent::class, 'dateNaissance', null, 16],
        'decisions' => [parent::class, 'decisions', null, 16],
        'demandeExplication' => [parent::class, 'demandeExplication', null, 16],
        'demandeExplications' => [parent::class, 'demandeExplications', null, 16],
        'depenses' => ['App\\Entity\\User', 'depenses', null, 16],
        'diabete' => [parent::class, 'diabete', null, 16],
        'documents' => [parent::class, 'documents', null, 16],
        'email' => ['App\\Entity\\User', 'email', null, 16],
        'employeFormations' => [parent::class, 'employeFormations', null, 16],
        'enabled' => ['App\\Entity\\User', 'enabled', null, 16],
        'enfant' => [parent::class, 'enfant', null, 16],
        'epilepsie' => [parent::class, 'epilepsie', null, 16],
        'evaluations' => [parent::class, 'evaluations', null, 16],
        'famillylink' => [parent::class, 'famillylink', null, 16],
        'famillyname' => [parent::class, 'famillyname', null, 16],
        'famillyphone' => [parent::class, 'famillyphone', null, 16],
        'feedback' => [parent::class, 'feedback', null, 16],
        'fonction' => ['App\\Entity\\User', 'fonction', null, 16],
        'formations' => [parent::class, 'formations', null, 16],
        'handicap' => [parent::class, 'handicap', null, 16],
        'heureSuplementaires' => [parent::class, 'heureSuplementaires', null, 16],
        'hireDate' => [parent::class, 'hireDate', null, 16],
        'hyper' => [parent::class, 'hyper', null, 16],
        'hypo' => [parent::class, 'hypo', null, 16],
        'id' => ['App\\Entity\\User', 'id', null, 16],
        'lieuNaissance' => [parent::class, 'lieuNaissance', null, 16],
        'livreur' => ['App\\Entity\\User', 'livreur', null, 16],
        'matricule' => [parent::class, 'matricule', null, 16],
        'messageReplies' => [parent::class, 'messageReplies', null, 16],
        'nationalite' => [parent::class, 'nationalite', null, 16],
        'nom' => ['App\\Entity\\User', 'nom', null, 16],
        'noteService' => [parent::class, 'noteService', null, 16],
        'noteServices' => [parent::class, 'noteServices', null, 16],
        'notifications' => [parent::class, 'notifications', null, 16],
        'paieSalaires' => [parent::class, 'paieSalaires', null, 16],
        'paies' => [parent::class, 'paies', null, 16],
        'password' => ['App\\Entity\\User', 'password', null, 16],
        'phone' => ['App\\Entity\\User', 'phone', null, 16],
        'poste' => [parent::class, 'poste', null, 16],
        'posteEmployes' => [parent::class, 'posteEmployes', null, 16],
        'prenom' => ['App\\Entity\\User', 'prenom', null, 16],
        'primePerformances' => [parent::class, 'primePerformances', null, 16],
        'primes' => [parent::class, 'primes', null, 16],
        'received' => ['App\\Entity\\User', 'received', null, 16],
        'remark' => [parent::class, 'remark', null, 16],
        'reponseExplications' => [parent::class, 'reponseExplications', null, 16],
        'resetToken' => ['App\\Entity\\User', 'resetToken', null, 16],
        'retenues' => [parent::class, 'retenues', null, 16],
        'roles' => [parent::class, 'roles', null, 8],
        'sanctions' => [parent::class, 'sanctions', null, 16],
        'sent' => ['App\\Entity\\User', 'sent', null, 16],
        'sexe' => [parent::class, 'sexe', null, 16],
        'status' => [parent::class, 'status', null, 16],
        'test' => [parent::class, 'test', null, 4],
        'transferts' => ['App\\Entity\\User', 'transferts', null, 16],
        'username' => ['App\\Entity\\User', 'username', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
