<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Banque extends \App\Entity\Banque implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'achats' => [parent::class, 'achats', null, 16],
        "\0".parent::class."\0".'compte' => [parent::class, 'compte', null, 16],
        "\0".parent::class."\0".'depenses' => [parent::class, 'depenses', null, 16],
        "\0".parent::class."\0".'financements' => [parent::class, 'financements', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null, 16],
        "\0".parent::class."\0".'paiements' => [parent::class, 'paiements', null, 16],
        "\0".parent::class."\0".'remboursements' => [parent::class, 'remboursements', null, 16],
        "\0".parent::class."\0".'transferts' => [parent::class, 'transferts', null, 16],
        "\0".parent::class."\0".'versements' => [parent::class, 'versements', null, 16],
        'achats' => [parent::class, 'achats', null, 16],
        'compte' => [parent::class, 'compte', null, 16],
        'depenses' => [parent::class, 'depenses', null, 16],
        'financements' => [parent::class, 'financements', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'nom' => [parent::class, 'nom', null, 16],
        'paiements' => [parent::class, 'paiements', null, 16],
        'remboursements' => [parent::class, 'remboursements', null, 16],
        'transferts' => [parent::class, 'transferts', null, 16],
        'versements' => [parent::class, 'versements', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
