<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class LivrerProduit extends \App\Entity\LivrerProduit implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'archive' => [parent::class, 'archive', null, 16],
        "\0".parent::class."\0".'commande' => [parent::class, 'commande', null, 16],
        "\0".parent::class."\0".'date' => [parent::class, 'date', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'livrer' => [parent::class, 'livrer', null, 16],
        "\0".parent::class."\0".'lot' => [parent::class, 'lot', null, 16],
        "\0".parent::class."\0".'peremption' => [parent::class, 'peremption', null, 16],
        "\0".parent::class."\0".'produit' => [parent::class, 'produit', null, 16],
        "\0".parent::class."\0".'promotion' => [parent::class, 'promotion', null, 16],
        "\0".parent::class."\0".'quantitecommander' => [parent::class, 'quantitecommander', null, 16],
        "\0".parent::class."\0".'quantitelivrer' => [parent::class, 'quantitelivrer', null, 16],
        "\0".parent::class."\0".'reste' => [parent::class, 'reste', null, 16],
        "\0".parent::class."\0".'restealivrer' => [parent::class, 'restealivrer', null, 16],
        "\0".parent::class."\0".'retour' => [parent::class, 'retour', null, 16],
        'archive' => [parent::class, 'archive', null, 16],
        'commande' => [parent::class, 'commande', null, 16],
        'date' => [parent::class, 'date', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'livrer' => [parent::class, 'livrer', null, 16],
        'lot' => [parent::class, 'lot', null, 16],
        'peremption' => [parent::class, 'peremption', null, 16],
        'produit' => [parent::class, 'produit', null, 16],
        'promotion' => [parent::class, 'promotion', null, 16],
        'quantitecommander' => [parent::class, 'quantitecommander', null, 16],
        'quantitelivrer' => [parent::class, 'quantitelivrer', null, 16],
        'reste' => [parent::class, 'reste', null, 16],
        'restealivrer' => [parent::class, 'restealivrer', null, 16],
        'retour' => [parent::class, 'retour', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
