<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Paie extends \App\Entity\Paie implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'date' => [parent::class, 'date', null, 16],
        "\0".parent::class."\0".'datepaye' => [parent::class, 'datepaye', null, 16],
        "\0".parent::class."\0".'detailsRetenues' => [parent::class, 'detailsRetenues', null, 16],
        "\0".parent::class."\0".'employe' => [parent::class, 'employe', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'impot' => [parent::class, 'impot', null, 16],
        "\0".parent::class."\0".'mois' => [parent::class, 'mois', null, 16],
        "\0".parent::class."\0".'payer' => [parent::class, 'payer', null, 16],
        "\0".parent::class."\0".'retenues' => [parent::class, 'retenues', null, 16],
        "\0".parent::class."\0".'salaireBase' => [parent::class, 'salaireBase', null, 16],
        "\0".parent::class."\0".'salaireBrut' => [parent::class, 'salaireBrut', null, 16],
        "\0".parent::class."\0".'salaireNet' => [parent::class, 'salaireNet', null, 16],
        "\0".parent::class."\0".'salaireNetImposable' => [parent::class, 'salaireNetImposable', null, 16],
        "\0".parent::class."\0".'totalChargeEmploye' => [parent::class, 'totalChargeEmploye', null, 16],
        "\0".parent::class."\0".'totalChargePatronal' => [parent::class, 'totalChargePatronal', null, 16],
        "\0".parent::class."\0".'totalPrime' => [parent::class, 'totalPrime', null, 16],
        "\0".parent::class."\0".'totalRetenue' => [parent::class, 'totalRetenue', null, 16],
        "\0".parent::class."\0".'totalheureSup' => [parent::class, 'totalheureSup', null, 16],
        'date' => [parent::class, 'date', null, 16],
        'datepaye' => [parent::class, 'datepaye', null, 16],
        'detailsRetenues' => [parent::class, 'detailsRetenues', null, 16],
        'employe' => [parent::class, 'employe', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'impot' => [parent::class, 'impot', null, 16],
        'mois' => [parent::class, 'mois', null, 16],
        'payer' => [parent::class, 'payer', null, 16],
        'retenues' => [parent::class, 'retenues', null, 16],
        'salaireBase' => [parent::class, 'salaireBase', null, 16],
        'salaireBrut' => [parent::class, 'salaireBrut', null, 16],
        'salaireNet' => [parent::class, 'salaireNet', null, 16],
        'salaireNetImposable' => [parent::class, 'salaireNetImposable', null, 16],
        'totalChargeEmploye' => [parent::class, 'totalChargeEmploye', null, 16],
        'totalChargePatronal' => [parent::class, 'totalChargePatronal', null, 16],
        'totalPrime' => [parent::class, 'totalPrime', null, 16],
        'totalRetenue' => [parent::class, 'totalRetenue', null, 16],
        'totalheureSup' => [parent::class, 'totalheureSup', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
