<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class DemandeExplication extends \App\Entity\DemandeExplication implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'date' => [parent::class, 'date', null, 16],
        "\0".parent::class."\0".'dateIncident' => [parent::class, 'dateIncident', null, 16],
        "\0".parent::class."\0".'decisions' => [parent::class, 'decisions', null, 16],
        "\0".parent::class."\0".'details' => [parent::class, 'details', null, 16],
        "\0".parent::class."\0".'employe' => [parent::class, 'employe', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'objet' => [parent::class, 'objet', null, 16],
        "\0".parent::class."\0".'reponseExplications' => [parent::class, 'reponseExplications', null, 16],
        "\0".parent::class."\0".'responsable' => [parent::class, 'responsable', null, 16],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null, 16],
        'date' => [parent::class, 'date', null, 16],
        'dateIncident' => [parent::class, 'dateIncident', null, 16],
        'decisions' => [parent::class, 'decisions', null, 16],
        'details' => [parent::class, 'details', null, 16],
        'employe' => [parent::class, 'employe', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'objet' => [parent::class, 'objet', null, 16],
        'reponseExplications' => [parent::class, 'reponseExplications', null, 16],
        'responsable' => [parent::class, 'responsable', null, 16],
        'status' => [parent::class, 'status', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
