<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Candidature extends \App\Entity\Candidature implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'activite' => [parent::class, 'activite', null, 16],
        "\0".parent::class."\0".'cv' => [parent::class, 'cv', null, 16],
        "\0".parent::class."\0".'datnaiss' => [parent::class, 'datnaiss', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'lieunaiss' => [parent::class, 'lieunaiss', null, 16],
        "\0".parent::class."\0".'niveau' => [parent::class, 'niveau', null, 16],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null, 16],
        "\0".parent::class."\0".'prenom' => [parent::class, 'prenom', null, 16],
        'activite' => [parent::class, 'activite', null, 16],
        'cv' => [parent::class, 'cv', null, 16],
        'datnaiss' => [parent::class, 'datnaiss', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'lieunaiss' => [parent::class, 'lieunaiss', null, 16],
        'niveau' => [parent::class, 'niveau', null, 16],
        'nom' => [parent::class, 'nom', null, 16],
        'prenom' => [parent::class, 'prenom', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
