<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Decision extends \App\Entity\Decision implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'absences' => [parent::class, 'absences', null, 16],
        "\0".parent::class."\0".'dateConfirm' => [parent::class, 'dateConfirm', null, 16],
        "\0".parent::class."\0".'dateDebut' => [parent::class, 'dateDebut', null, 16],
        "\0".parent::class."\0".'dateDecision' => [parent::class, 'dateDecision', null, 16],
        "\0".parent::class."\0".'dateFin' => [parent::class, 'dateFin', null, 16],
        "\0".parent::class."\0".'demandes' => [parent::class, 'demandes', null, 16],
        "\0".parent::class."\0".'explication' => [parent::class, 'explication', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'motif' => [parent::class, 'motif', null, 16],
        "\0".parent::class."\0".'responsable' => [parent::class, 'responsable', null, 16],
        "\0".parent::class."\0".'type' => [parent::class, 'type', null, 16],
        "\0".parent::class."\0".'typeSanction' => [parent::class, 'typeSanction', null, 16],
        'absences' => [parent::class, 'absences', null, 16],
        'dateConfirm' => [parent::class, 'dateConfirm', null, 16],
        'dateDebut' => [parent::class, 'dateDebut', null, 16],
        'dateDecision' => [parent::class, 'dateDecision', null, 16],
        'dateFin' => [parent::class, 'dateFin', null, 16],
        'demandes' => [parent::class, 'demandes', null, 16],
        'explication' => [parent::class, 'explication', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'motif' => [parent::class, 'motif', null, 16],
        'responsable' => [parent::class, 'responsable', null, 16],
        'type' => [parent::class, 'type', null, 16],
        'typeSanction' => [parent::class, 'typeSanction', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
