<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Commande extends \App\Entity\Commande implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'Montant' => [parent::class, 'Montant', null, 16],
        "\0".parent::class."\0".'admin' => [parent::class, 'admin', null, 16],
        "\0".parent::class."\0".'commandeProduits' => [parent::class, 'commandeProduits', null, 16],
        "\0".parent::class."\0".'credit' => [parent::class, 'credit', null, 16],
        "\0".parent::class."\0".'date' => [parent::class, 'date', null, 16],
        "\0".parent::class."\0".'dateefectlivraison' => [parent::class, 'dateefectlivraison', null, 16],
        "\0".parent::class."\0".'datelivrer' => [parent::class, 'datelivrer', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'livraison' => [parent::class, 'livraison', null, 16],
        "\0".parent::class."\0".'livrer' => [parent::class, 'livrer', null, 16],
        "\0".parent::class."\0".'livreur' => [parent::class, 'livreur', null, 16],
        "\0".parent::class."\0".'paiement' => [parent::class, 'paiement', null, 16],
        "\0".parent::class."\0".'payer' => [parent::class, 'payer', null, 16],
        "\0".parent::class."\0".'reduction' => [parent::class, 'reduction', null, 16],
        "\0".parent::class."\0".'suivi' => [parent::class, 'suivi', null, 16],
        "\0".parent::class."\0".'tva' => [parent::class, 'tva', null, 16],
        "\0".parent::class."\0".'user' => [parent::class, 'user', null, 16],
        "\0".parent::class."\0".'versement' => [parent::class, 'versement', null, 16],
        "\0".parent::class."\0".'versements' => [parent::class, 'versements', null, 16],
        'Montant' => [parent::class, 'Montant', null, 16],
        'admin' => [parent::class, 'admin', null, 16],
        'commandeProduits' => [parent::class, 'commandeProduits', null, 16],
        'credit' => [parent::class, 'credit', null, 16],
        'date' => [parent::class, 'date', null, 16],
        'dateefectlivraison' => [parent::class, 'dateefectlivraison', null, 16],
        'datelivrer' => [parent::class, 'datelivrer', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'livraison' => [parent::class, 'livraison', null, 16],
        'livrer' => [parent::class, 'livrer', null, 16],
        'livreur' => [parent::class, 'livreur', null, 16],
        'paiement' => [parent::class, 'paiement', null, 16],
        'payer' => [parent::class, 'payer', null, 16],
        'reduction' => [parent::class, 'reduction', null, 16],
        'suivi' => [parent::class, 'suivi', null, 16],
        'tva' => [parent::class, 'tva', null, 16],
        'user' => [parent::class, 'user', null, 16],
        'versement' => [parent::class, 'versement', null, 16],
        'versements' => [parent::class, 'versements', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
