<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class RetourProduit extends \App\Entity\RetourProduit implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'avoir' => [parent::class, 'avoir', null, 16],
        "\0".parent::class."\0".'commande' => [parent::class, 'commande', null, 16],
        "\0".parent::class."\0".'date' => [parent::class, 'date', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'lot' => [parent::class, 'lot', null, 16],
        "\0".parent::class."\0".'motif' => [parent::class, 'motif', null, 16],
        "\0".parent::class."\0".'peremption' => [parent::class, 'peremption', null, 16],
        "\0".parent::class."\0".'produit' => [parent::class, 'produit', null, 16],
        "\0".parent::class."\0".'quantite' => [parent::class, 'quantite', null, 16],
        "\0".parent::class."\0".'reapprovisionner' => [parent::class, 'reapprovisionner', null, 16],
        "\0".parent::class."\0".'rembourser' => [parent::class, 'rembourser', null, 16],
        "\0".parent::class."\0".'retour' => [parent::class, 'retour', null, 16],
        "\0".parent::class."\0".'stock' => [parent::class, 'stock', null, 16],
        "\0".parent::class."\0".'valider' => [parent::class, 'valider', null, 16],
        'avoir' => [parent::class, 'avoir', null, 16],
        'commande' => [parent::class, 'commande', null, 16],
        'date' => [parent::class, 'date', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'lot' => [parent::class, 'lot', null, 16],
        'motif' => [parent::class, 'motif', null, 16],
        'peremption' => [parent::class, 'peremption', null, 16],
        'produit' => [parent::class, 'produit', null, 16],
        'quantite' => [parent::class, 'quantite', null, 16],
        'reapprovisionner' => [parent::class, 'reapprovisionner', null, 16],
        'rembourser' => [parent::class, 'rembourser', null, 16],
        'retour' => [parent::class, 'retour', null, 16],
        'stock' => [parent::class, 'stock', null, 16],
        'valider' => [parent::class, 'valider', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
