<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Conges extends \App\Entity\Conges implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'confirmer' => [parent::class, 'confirmer', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'dateDebut' => [parent::class, 'dateDebut', null, 16],
        "\0".parent::class."\0".'dateDebutAccorder' => [parent::class, 'dateDebutAccorder', null, 16],
        "\0".parent::class."\0".'dateFin' => [parent::class, 'dateFin', null, 16],
        "\0".parent::class."\0".'dateFinAccorder' => [parent::class, 'dateFinAccorder', null, 16],
        "\0".parent::class."\0".'dateModifier' => [parent::class, 'dateModifier', null, 16],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null, 16],
        "\0".parent::class."\0".'employe' => [parent::class, 'employe', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null, 16],
        "\0".parent::class."\0".'type' => [parent::class, 'type', null, 16],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null, 16],
        'confirmer' => [parent::class, 'confirmer', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'dateDebut' => [parent::class, 'dateDebut', null, 16],
        'dateDebutAccorder' => [parent::class, 'dateDebutAccorder', null, 16],
        'dateFin' => [parent::class, 'dateFin', null, 16],
        'dateFinAccorder' => [parent::class, 'dateFinAccorder', null, 16],
        'dateModifier' => [parent::class, 'dateModifier', null, 16],
        'description' => [parent::class, 'description', null, 16],
        'employe' => [parent::class, 'employe', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'status' => [parent::class, 'status', null, 16],
        'type' => [parent::class, 'type', null, 16],
        'updatedAt' => [parent::class, 'updatedAt', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
